import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import Header from "@/components/header";
import FloatingShapes from "@/components/floating-shapes";
import { ConvexClientProvider } from "./ConvexClientProvider";
import {ClerkProvider} from "@clerk/nextjs"
import {shadesOfPurple} from "@clerk/themes"
const inter = Inter({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Pixxel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkProvider appearance={{
              baseTheme: shadesOfPurple,
            }}>

            <ConvexClientProvider>
            <Header />
            <main className="bg-slate-900 min-h-screen text-white overflow-x-hidden">
            <FloatingShapes />
            <Toaster richColors />
            {children}
            </main>
            </ConvexClientProvider>
            </ClerkProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
